# Generated by Django 4.1 on 2023-04-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_created_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_update_date',
        ),
    ]
